#!/usr/bin/env python3
"""Validate canonical CSVs and generate the broad comparison, offline."""
import csv
import json
from pathlib import Path
from extract_legacy import write_csv
from crime import compile_crime, export_source_tables
from crime_coverage import export_coverage
from crime_boundaries import export_boundaries
from crime_residuals import export_residuals
from crime_outliers import export_outliers
from screening import compile_screening

ROOT = Path(__file__).resolve().parents[1]
GROUPS = ('buy', 'rent', 'market', 'localTransport', 'nationalTransport', 'quiet', 'condition')
NUMERIC = {'lat', 'lon', 'proxyMedian', 'transactions', 'proxyMonthly', 'oneBedCount', 'londonMinutes', 'londonChanges', 'birminghamMinutes', 'birminghamChanges'}


def read(path):
    with path.open(newline='', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        if not reader.fieldnames or len(set(reader.fieldnames)) != len(reader.fieldnames):
            raise ValueError(f'{path}: missing or duplicate columns')
        rows = list(reader)
    for row in rows:
        if None in row or None in row.values():
            raise ValueError(f'{path}: malformed CSV row')
        for key, value in row.items():
            if key in NUMERIC:
                if not value:
                    row[key] = None
                    continue
                number = float(value)
                import math
                if not math.isfinite(number) or (key not in ('lat', 'lon') and number < 0):
                    raise ValueError(f'{path}: invalid {key}: {value}')
                if key not in ('lat', 'lon') and not number.is_integer():
                    raise ValueError(f'{path}: expected whole number for {key}')
                row[key] = number if key in ('lat', 'lon') else int(number)
    return rows


def compile_data(inputs):
    locations = read(inputs / 'locations.csv')
    by_id = {}
    for row in locations:
        if not row.get('id') or row['id'] in by_id:
            raise ValueError('Missing or duplicate location id')
        if not row.get('name') or not row.get('country'):
            raise ValueError('Location needs a name and country')
        for key, limit in [('lat', 90), ('lon', 180)]:
            if row.get(key) is not None and abs(row[key]) > limit:
                raise ValueError(f'Invalid {key}')
        by_id[row['id']] = row
    if not locations:
        raise ValueError('No locations')
    for group in GROUPS:
        seen = set()
        for row in read(inputs / f'{group}.csv'):
            ident = row.pop('location_id')
            if ident not in by_id or ident in seen:
                raise ValueError(f'{group}: orphan or duplicate location_id {ident}')
            seen.add(ident)
            by_id[ident][group] = row
        for location in locations:
            location.setdefault(group, {})  # New locations may have unknown metrics.
    sources = read(inputs / 'sources.csv')
    for source in sources:
        if source['location_id'] not in by_id:
            raise ValueError('Source references unknown location')
        if not source['url'].startswith(('https://', 'http://')):
            raise ValueError('Source URL must use http(s)')
    evidence = read(inputs / 'evidence.csv')
    if len({r['id'] for r in evidence}) != len(evidence):
        raise ValueError('Duplicate evidence id')
    return dict(locations=locations, sources=sources, evidence=evidence)


def build():
    data = compile_data(ROOT / 'data/inputs')
    crime = compile_crime(ROOT / 'data/inputs', data['locations'], data['evidence'])
    data['screening'] = compile_screening(data['locations'], crime)
    export_source_tables(ROOT)
    export_coverage(ROOT)
    export_boundaries(ROOT)
    export_residuals(ROOT)
    export_outliers(ROOT)
    write_csv(ROOT / 'data/derived/crime_research.csv', crime)
    # Separate recorded-offence research rows; never use them in broad-screen sorts.
    data['crimeResearch'] = [row for row in crime if row['category'] != 'asb']
    rows = []
    for location in data['locations']:
        row = {k: v for k, v in location.items() if not isinstance(v, dict)}
        for group in GROUPS:
            row.update({f'{group}.{k}': v for k, v in location[group].items()})
        screening = data['screening']['results'][location['id']]
        row['screening.safety'] = screening['safety']
        for tenure in ('buy', 'rent'):
            row[f'screening.{tenure}.score'] = screening['tenures'][tenure]['score']
            row[f'screening.{tenure}.band'] = screening['tenures'][tenure]['band']
            for factor, value in screening['tenures'][tenure]['factors'].items():
                row[f'screening.{tenure}.{factor}'] = value
        rows.append(row)
    write_csv(ROOT / 'data/derived/broad_screen.csv', rows)
    payload = json.dumps(data, ensure_ascii=False, indent=2, allow_nan=False)
    (ROOT / 'web/data.js').write_text('// Generated by scripts/build.py; do not edit.\nwindow.FLATS_DATA = ' + payload + ';\n', encoding='utf-8')
    print(f'Built broad screen for {len(rows)} locations with separate buy/rent screening scores.')


if __name__ == '__main__':
    build()
